import pytest
from uuid import uuid4
from datetime import date
from decimal import Decimal
from unittest.mock import AsyncMock, patch

from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import User
from app.db.models.enums import SourceType
from app.ai.engine import AIEngine
from app.trips.service import TripService
from app.trips.schemas import TripCreate, TripDayIn

pytestmark = pytest.mark.asyncio


def _make_mock_client() -> object:
    """Build a fake Gemini client whose .aio.models.generate_content is patchable."""
    model = AsyncMock()
    model.generate_content = AsyncMock()
    aio = AsyncMock()
    aio.models = AsyncMock()
    aio.models.generate_content = model.generate_content
    client = AsyncMock()
    client.aio = aio
    return client


@pytest.fixture
def mock_engine_client():
    """Patch app.ai.engine.get_client to return a fake Gemini client."""
    with patch("app.ai.engine.get_client") as mock_get:
        mock_client = _make_mock_client()
        mock_get.return_value = mock_client
        yield mock_client


async def _make_user(db: AsyncSession, email: str) -> User:
    user = User(firebase_uid=f"fb_{email}", email=email, display_name="Test User")
    db.add(user)
    await db.flush()
    return user


async def _make_trip(db: AsyncSession, user: User) -> tuple[TripService, object]:
    service = TripService(db)
    trip = await service.create(
        user,
        TripCreate(
            title="AI Test Trip",
            destination_name="Paris",
            destination_city="Paris",
            destination_country="France",
            origin_city="London",
            start_date=date(2025, 10, 1),
            end_date=date(2025, 10, 7),
            duration_days=6,
            group_type="solo",
            travel_purpose="leisure",
            budget_total=Decimal("1000.00"),
            currency="USD",
        ),
    )
    return service, trip


async def test_ai_engine_converse_add_item(get_test_db: AsyncSession, mock_engine_client):
    """Test AI engine adds an item when user requests it."""
    user = await _make_user(get_test_db, "test@example.com")
    trip_service, trip = await _make_trip(get_test_db, user)

    day_in = TripDayIn(date=date(2025, 10, 2), title="Day 2: Louvre", is_transit_day=False)
    trip_with_day = await trip_service.add_day(trip, user.id, day_in)
    day_id = trip_with_day.days[0].id

    mock_client = mock_engine_client
    ai_engine = AIEngine(get_test_db)

    mock_response = AsyncMock()
    mock_response.text = (
        '{\n'
        '  "thoughts": "The user wants to add the Eiffel Tower to their itinerary.",\n'
        '  "reply": "I\'ve added the Eiffel Tower to your day 2.",\n'
        '  "mutations": [\n'
        '    {\n'
        '      "action": "add_item",\n'
        f'      "day_id": "{day_id}",\n'
        '      "name": "Eiffel Tower",\n'
        '      "item_type": "attraction",\n'
        '      "estimated_price_inr": 2500.0,\n'
        '      "position_after_item": null\n'
        '    }\n'
        '  ]\n'
        '}'
    )

    with patch.object(
        mock_client.aio.models, "generate_content", return_value=mock_response
    ) as mock_generate:
        ai_response, updated_trip_read = await ai_engine.converse(
            trip_id=trip.id,
            user_id=user.id,
            user_message="Add the Eiffel Tower to my day 2.",
        )

    mock_generate.assert_called_once()

    assert ai_response.thoughts == "The user wants to add the Eiffel Tower to their itinerary."
    assert ai_response.reply == "I've added the Eiffel Tower to your day 2."

    assert len(ai_response.mutations) == 1
    mutation = ai_response.mutations[0]
    assert mutation.action == "add_item"
    assert mutation.day_id == day_id
    assert mutation.name == "Eiffel Tower"
    assert mutation.item_type == "attraction"
    assert mutation.estimated_price_inr == 2500.0

    updated_trip = await trip_service.get(trip.id)
    assert len(updated_trip.days[0].items) == 1
    item = updated_trip.days[0].items[0]
    assert item.name == "Eiffel Tower"
    assert item.item_type == "attraction"
    assert item.pricing == {"amount": "2500.0", "source": "ESTIMATED"}
    assert item.source_type == SourceType.AI_GENERATED
    assert item.metadata_json == {"CopilotNote": "Generated by AI"}


async def test_ai_engine_converse_no_mutation(get_test_db: AsyncSession, mock_engine_client):
    """Test AI engine returns no mutations when user asks a question."""
    user = await _make_user(get_test_db, "test2@example.com")
    trip_service, trip = await _make_trip(get_test_db, user)

    mock_client = mock_engine_client
    ai_engine = AIEngine(get_test_db)

    mock_response = AsyncMock()
    mock_response.text = (
        '{\n'
        '  "thoughts": "The user is asking about the weather, which doesn\'t require changing the trip.",\n'
        '  "reply": "The weather in Rome is usually pleasant in November, but pack a light jacket just in case.",\n'
        '  "mutations": []\n'
        '}'
    )

    with patch.object(
        mock_client.aio.models, "generate_content", return_value=mock_response
    ) as mock_generate:
        ai_response, _ = await ai_engine.converse(
            trip_id=trip.id,
            user_id=user.id,
            user_message="What's the weather like in Rome?",
        )

    mock_generate.assert_called_once()
    assert len(ai_response.mutations) == 0

    updated_trip = await trip_service.get(trip.id)
    assert len(updated_trip.days) == 0  # No days added


async def test_ai_engine_converse_error_handling(get_test_db: AsyncSession, mock_engine_client):
    """Test AI engine propagates errors from the Gemini client."""
    user = await _make_user(get_test_db, "test3@example.com")
    trip_service, trip = await _make_trip(get_test_db, user)

    mock_client = mock_engine_client
    ai_engine = AIEngine(get_test_db)

    with patch.object(
        mock_client.aio.models,
        "generate_content",
        side_effect=Exception("Gemini API error"),
    ):
        with pytest.raises(Exception, match="Gemini API error"):
            await ai_engine.converse(
                trip_id=trip.id,
                user_id=user.id,
                user_message="Add something to my trip.",
            )
