"""initial schema

Revision ID: 7293cdc8c482
Revises: 
Create Date: 2026-09-08 19:39:57.132943

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from app.db.base import JsonB

# revision identifiers, used by Alembic.
revision: str = '7293cdc8c482'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('LIVE_API', 'MANUAL', 'INTERNAL', 'AGGREGATOR', name='supplierkind'), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('credentials_ref', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capabilities', JsonB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('name', name=op.f('uq_suppliers_name'))
    )
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('home_city', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('preferences', JsonB(), nullable=False),
    sa.Column('ai_profile', JsonB(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('supplier_offers',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('FLIGHT', 'HOTEL', 'TRAIN', 'CAB', 'ACTIVITY', 'INSURANCE', 'PACKAGE', 'OTHER', name='itemkind'), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('availability', JsonB(), nullable=False),
    sa.Column('terms', JsonB(), nullable=False),
    sa.Column('raw_payload', JsonB(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'EXPIRED', 'USED', 'REVOKED', name='offerstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_offers_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_offers')),
    sa.UniqueConstraint('supplier_id', 'external_id', name='uq_supplier_external')
    )
    op.create_index(op.f('ix_supplier_offers_city'), 'supplier_offers', ['city'], unique=False)
    op.create_index(op.f('ix_supplier_offers_expires_at'), 'supplier_offers', ['expires_at'], unique=False)
    op.create_index(op.f('ix_supplier_offers_kind'), 'supplier_offers', ['kind'], unique=False)
    op.create_index(op.f('ix_supplier_offers_status'), 'supplier_offers', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_offers_supplier_id'), 'supplier_offers', ['supplier_id'], unique=False)
    op.create_table('trips',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('destination_name', sa.String(length=200), nullable=False),
    sa.Column('destination_city', sa.String(length=120), nullable=True),
    sa.Column('destination_country', sa.String(length=120), nullable=True),
    sa.Column('origin_city', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.SmallInteger(), nullable=False),
    sa.Column('group_type', sa.String(length=40), nullable=True),
    sa.Column('travel_purpose', sa.String(length=40), nullable=True),
    sa.Column('budget_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNING', 'READY', 'PARTIALLY_BOOKED', 'BOOKED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ARCHIVED', name='tripstatus'), nullable=False),
    sa.Column('status_reason', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.Enum('VERIFIED_LIVE', 'VERIFIED_STATIC', 'USER_PROVIDED', 'ESTIMATED', 'AI_GENERATED', 'PLACEHOLDER', 'UNAVAILABLE', name='sourcetype'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('data', JsonB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['trip_versions.id'], name=op.f('fk_trips_current_version_id_trip_versions'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    op.create_index(op.f('ix_trips_destination_name'), 'trips', ['destination_name'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('user_events',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('properties', JsonB(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_events'))
    )
    op.create_index(op.f('ix_user_events_event_name'), 'user_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('booking_number', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('FLIGHT', 'HOTEL', 'TRAIN', 'CAB', 'ACTIVITY', 'INSURANCE', 'PACKAGE', 'OTHER', name='itemkind'), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SELECTED', 'PRICE_CHECK_REQUIRED', 'PRICING', 'PRICE_CONFIRMED', 'PAYMENT_PENDING', 'PAYMENT_VERIFIED', 'BOOKING_PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED', 'REFUNDED', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_offer_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_booking_ref', sa.String(length=160), nullable=True),
    sa.Column('pnr', sa.String(length=20), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('traveler_details', JsonB(), nullable=False),
    sa.Column('metadata', JsonB(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_bookings_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_offer_id'], ['supplier_offers.id'], name=op.f('fk_bookings_supplier_offer_id_supplier_offers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_bookings_trip_id_trips'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.create_index(op.f('ix_bookings_idempotency_key'), 'bookings', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_bookings_kind'), 'bookings', ['kind'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_supplier_booking_ref'), 'bookings', ['supplier_booking_ref'], unique=False)
    op.create_index(op.f('ix_bookings_trip_id'), 'bookings', ['trip_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('metadata', JsonB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_reviews_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('trip_id', 'user_id', name='uq_review_trip_user')
    )
    op.create_index(op.f('ix_reviews_trip_id'), 'reviews', ['trip_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('saved_trips',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_saved_trips_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_trips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_trips'))
    )
    op.create_index(op.f('ix_saved_trips_trip_id'), 'saved_trips', ['trip_id'], unique=False)
    op.create_index(op.f('ix_saved_trips_user_id'), 'saved_trips', ['user_id'], unique=False)
    op.create_table('supplier_transactions',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('tx_type', sa.Enum('SEARCH', 'PRICE_CHECK', 'HOLD', 'CONFIRM', 'CANCEL', 'REFUND', 'STATUS', 'ISSUE', name='suppliertxtype'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('supplier_request_id', sa.String(length=160), nullable=True),
    sa.Column('request_payload', JsonB(), nullable=False),
    sa.Column('response_payload', JsonB(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'TIMEOUT', name='transactionstatus'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['supplier_offers.id'], name=op.f('fk_supplier_transactions_offer_id_supplier_offers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_transactions_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_transactions'))
    )
    op.create_index(op.f('ix_supplier_transactions_idempotency_key'), 'supplier_transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_supplier_transactions_supplier_id'), 'supplier_transactions', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_transactions_supplier_request_id'), 'supplier_transactions', ['supplier_request_id'], unique=False)
    op.create_index(op.f('ix_supplier_transactions_tx_type'), 'supplier_transactions', ['tx_type'], unique=False)
    op.create_table('trip_days',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('day_number', sa.SmallInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('is_transit_day', sa.Boolean(), nullable=False),
    sa.Column('weather', JsonB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_days_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_days')),
    sa.UniqueConstraint('trip_id', 'day_number', name='uq_trip_day_number')
    )
    op.create_index(op.f('ix_trip_days_trip_id'), 'trip_days', ['trip_id'], unique=False)
    op.create_table('trip_events',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.Enum('USER', 'AI', 'SYSTEM', name='actortype'), nullable=False),
    sa.Column('action_id', sa.String(length=80), nullable=True),
    sa.Column('payload', JsonB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_events_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trip_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_events'))
    )
    op.create_index(op.f('ix_trip_events_event_type'), 'trip_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_trip_events_trip_id'), 'trip_events', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_events_user_id'), 'trip_events', ['user_id'], unique=False)
    op.create_table('trip_preferences',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('interests', JsonB(), nullable=False),
    sa.Column('dietary_preferences', JsonB(), nullable=False),
    sa.Column('accessibility_needs', JsonB(), nullable=False),
    sa.Column('pace', sa.String(length=20), nullable=True),
    sa.Column('hotel_area', sa.String(length=120), nullable=True),
    sa.Column('must_do', JsonB(), nullable=False),
    sa.Column('browsing_signals', JsonB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_preferences_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_preferences')),
    sa.UniqueConstraint('trip_id', name=op.f('uq_trip_preferences_trip_id'))
    )
    op.create_table('trip_versions',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', JsonB(), nullable=False),
    sa.Column('change_description', sa.String(length=300), nullable=True),
    sa.Column('action_id', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.Enum('USER', 'AI', 'SYSTEM', name='actortype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_versions_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_versions'))
    )
    op.create_index(op.f('ix_trip_versions_trip_id'), 'trip_versions', ['trip_id'], unique=False)
    op.create_table('booking_items',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('from_place', sa.String(length=120), nullable=True),
    sa.Column('to_place', sa.String(length=120), nullable=True),
    sa.Column('passenger_names', JsonB(), nullable=False),
    sa.Column('metadata', JsonB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_items_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_items'))
    )
    op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_refunded', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ATTEMPTED', 'CAPTURED', 'VERIFIED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_errors', JsonB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('booking_id', 'razorpay_order_id', name='uq_booking_order')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('trip_items',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('day_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('coords_source', sa.Enum('VERIFIED_LIVE', 'VERIFIED_STATIC', 'USER_PROVIDED', 'ESTIMATED', 'AI_GENERATED', 'PLACEHOLDER', 'UNAVAILABLE', name='sourcetype'), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('is_must_do', sa.Boolean(), nullable=False),
    sa.Column('pricing', JsonB(), nullable=False),
    sa.Column('source_type', sa.Enum('VERIFIED_LIVE', 'VERIFIED_STATIC', 'USER_PROVIDED', 'ESTIMATED', 'AI_GENERATED', 'PLACEHOLDER', 'UNAVAILABLE', name='sourcetype'), nullable=False),
    sa.Column('supplier_offer_id', sa.Uuid(), nullable=True),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', JsonB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_trip_items_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['day_id'], ['trip_days.id'], name=op.f('fk_trip_items_day_id_trip_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_offer_id'], ['supplier_offers.id'], name=op.f('fk_trip_items_supplier_offer_id_supplier_offers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_items_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_items'))
    )
    op.create_index(op.f('ix_trip_items_day_id'), 'trip_items', ['day_id'], unique=False)
    op.create_index(op.f('ix_trip_items_trip_id'), 'trip_items', ['trip_id'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_no', sa.SmallInteger(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('metadata', JsonB(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_attempts_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_attempts'))
    )
    op.create_index(op.f('ix_payment_attempts_payment_id'), 'payment_attempts', ['payment_id'], unique=False)
    op.create_table('refunds',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('razorpay_refund_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=240), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_refunds_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index(op.f('ix_refunds_booking_id'), 'refunds', ['booking_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_razorpay_refund_id'), 'refunds', ['razorpay_refund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_razorpay_refund_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_booking_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payment_attempts_payment_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_trip_items_trip_id'), table_name='trip_items')
    op.drop_index(op.f('ix_trip_items_day_id'), table_name='trip_items')
    op.drop_table('trip_items')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index(op.f('ix_trip_versions_trip_id'), table_name='trip_versions')
    op.drop_table('trip_versions')
    op.drop_table('trip_preferences')
    op.drop_index(op.f('ix_trip_events_user_id'), table_name='trip_events')
    op.drop_index(op.f('ix_trip_events_trip_id'), table_name='trip_events')
    op.drop_index(op.f('ix_trip_events_event_type'), table_name='trip_events')
    op.drop_table('trip_events')
    op.drop_index(op.f('ix_trip_days_trip_id'), table_name='trip_days')
    op.drop_table('trip_days')
    op.drop_index(op.f('ix_supplier_transactions_tx_type'), table_name='supplier_transactions')
    op.drop_index(op.f('ix_supplier_transactions_supplier_request_id'), table_name='supplier_transactions')
    op.drop_index(op.f('ix_supplier_transactions_supplier_id'), table_name='supplier_transactions')
    op.drop_index(op.f('ix_supplier_transactions_idempotency_key'), table_name='supplier_transactions')
    op.drop_table('supplier_transactions')
    op.drop_index(op.f('ix_saved_trips_user_id'), table_name='saved_trips')
    op.drop_index(op.f('ix_saved_trips_trip_id'), table_name='saved_trips')
    op.drop_table('saved_trips')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_trip_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_trip_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_supplier_booking_ref'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_kind'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_idempotency_key'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_name'), table_name='user_events')
    op.drop_table('user_events')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination_name'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_supplier_offers_supplier_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_status'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_kind'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_expires_at'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_city'), table_name='supplier_offers')
    op.drop_table('supplier_offers')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
